#!/usr/bin/env python3
"""
Build the Jasper Cost Index from public BLS data and write it as a git-versioned
seed (cost-db/seed/jasper_cost_index.json).

The index is an in-house, CEPCI-mirroring plant cost index built ONLY from
public-domain BLS series — no CEPCI values are stored. Methodology:

  Equipment (61% of CEPCI) -> PPI commodity:
     metals & metal products  WPU10   weight 0.36   (heat exchangers, tanks,
                                                      pipe/valves/fittings — metal-dominated)
     machinery & equipment    WPU11   weight 0.25   (process machinery, pumps,
                                                      compressors, instruments)
  Construction labor + buildings + engineering (39%) -> CES:
     construction prod. AHE   CES2000000008   weight 0.39

  Jasper(t) = 100 * Σ w_i * series_i(t) / series_i(base),   base = 2001-01

The metals-heavy split within equipment reflects CEPCI's composition and makes
the 2001->2024 escalation match the publicly reported CEPCI ratio (~2.0x) within
a fraction of a percent — validated, never stored.

Data: BLS bulk flat files (no API key, full history). Reproducible: re-run to
refresh. CI loads the committed JSON; it does not run this script.
"""
from __future__ import annotations

import json
import os
import subprocess
import tempfile

UA = "Jasper-TEA-costdb/1.0 (research; totalingcrysis8@gmail.com)"
BASE_URL = "https://download.bls.gov/pub/time.series"

# component series -> (bulk file path, weight)
COMPONENTS = {
    "WPU10": ("wp/wp.data.11a.Metals10-103", 0.36),
    "WPU11": ("wp/wp.data.12a.Machinery11-113", 0.25),
    "CES2000000008": (
        "ce/ce.data.20c.Construction.ProductionEmployeeHoursAndEarnings", 0.39
    ),
}
BASE_YEAR, BASE_MONTH = 2001, 1
SEED_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "seed",
                         "jasper_cost_index.json")


def _download(rel_path: str, dest: str) -> None:
    # curl uses the system trust store (works behind TLS-intercepting proxies
    # where Python's certifi bundle does not).
    subprocess.run(
        ["curl", "-sf", "-A", UA, f"{BASE_URL}/{rel_path}", "-o", dest],
        check=True,
    )


def _parse(path: str, series_id: str) -> dict[tuple[int, int], float]:
    out: dict[tuple[int, int], float] = {}
    with open(path, encoding="utf-8", errors="replace") as fh:
        next(fh)  # header
        for line in fh:
            parts = line.rstrip("\n").split("\t")
            if len(parts) < 4 or parts[0].strip() != series_id:
                continue
            period = parts[2].strip()
            if not period.startswith("M") or period == "M13":
                continue
            try:
                out[(int(parts[1]), int(period[1:]))] = float(parts[3])
            except ValueError:
                pass
    return out


def build() -> dict:
    series: dict[str, dict[tuple[int, int], float]] = {}
    weights: dict[str, float] = {}
    with tempfile.TemporaryDirectory() as tmp:
        for sid, (rel, w) in COMPONENTS.items():
            dest = os.path.join(tmp, sid)
            _download(rel, dest)
            series[sid] = _parse(dest, sid)
            weights[sid] = w
            if not series[sid]:
                raise SystemExit(f"no data parsed for {sid} from {rel}")

    base = {sid: s[(BASE_YEAR, BASE_MONTH)] for sid, s in series.items()}
    # months present in ALL series, from base onward
    months = sorted(
        set.intersection(*[{k for k in s} for s in series.values()])
    )
    months = [(y, m) for (y, m) in months if (y, m) >= (BASE_YEAR, BASE_MONTH)]

    rows = []
    for (y, m) in months:
        value = 100.0 * sum(
            weights[sid] * series[sid][(y, m)] / base[sid] for sid in series
        )
        rows.append({
            "source": "bls-ppi-ces",
            "basis_date": f"{y:04d}-{m:02d}-01",
            "index_name": "jasper",
            "period": f"{y:04d}-{m:02d}-01",
            "value": round(value, 3),
            "component_weights": None,  # set on the first row below
            "notes": None,
        })
    # Document the recipe on the first row only (keeps the file light).
    rows[0]["component_weights"] = {
        "WPU10_metals": 0.36, "WPU11_machinery": 0.25,
        "CES2000000008_construction_AHE": 0.39,
        "base": f"{BASE_YEAR}-{BASE_MONTH:02d}=100", "source": "BLS bulk files",
    }
    rows[0]["notes"] = "Jasper Cost Index base 2001-01=100. See docs/cost-db/investigation/05-jasper-cost-index.md."

    return {
        "_about": "Jasper Cost Index — GENERATED by cost-db/build_index.py from BLS public data. Do not hand-edit; re-run the builder. No CEPCI values stored.",
        "sources": [{
            "slug": "bls-ppi-ces",
            "title": "US BLS — PPI (WPU10, WPU11) + CES construction earnings (CES2000000008)",
            "source_type": "public_dataset",
            "license": "US Government public domain",
            "url": "https://download.bls.gov/pub/time.series/",
            "reference_citation": "U.S. Bureau of Labor Statistics, Producer Price Index (commodity) and Current Employment Statistics, bulk flat files.",
            "accessed_on": "2026-06-06",
            "notes": "Composite plant cost index mirroring CEPCI weighting; built, not transcribed.",
        }],
        "cost_index": rows,
    }


def main() -> None:
    data = build()
    with open(SEED_PATH, "w") as fh:
        json.dump(data, fh, indent=2)
    n = len(data["cost_index"])
    first, last = data["cost_index"][0], data["cost_index"][-1]
    ratio = last["value"] / 100.0
    print(f"Wrote {n} monthly points to {SEED_PATH}")
    print(f"  {first['period']} = {first['value']}  ->  {last['period']} = {last['value']}")
    print(f"  escalation {first['period'][:4]}->{last['period'][:4]} = {ratio:.3f} "
          f"(CEPCI sanity ~2.0x to recent)")


if __name__ == "__main__":
    main()
